### ISSUE TITLE
ERROR:wmt2017-transformer/run-me.sh

### ISSUE THREAD

**Issue by wangxw1023** [marian-nmt/marian-examples#18]
Hi, there is a error in wmt2017-transformer/run-me.sh.
line 30:if [ ! -e MARIAN_TRAIN ]
Correct:if [ ! -e $MARIAN_TRAIN ]

**Comment by snukky** [comment]
Thanks. It has been already fixed here: https://github.com/marian-nmt/marian-examples/pull/13 and will take effect when we update git modules in the main repository.
