### ISSUE TITLE
File 'data/corpus.bpe.en' is empty

### ISSUE THREAD

**Issue by Sarah-Callies** [marian-nmt/marian-examples#21]
**Error: File 'data/corpus.bpe.en' is empty
Error: Aborted from marian::data::CorpusBase::CorpusBase(marian::Ptr<marian::Options>, bool) in /120Tdata/yandaowei/marian/src/data/corpus_base.cpp:348**

**Comment by snukky** [comment]
Hi, which example was it? Was there any error in downloading data or from subword-nmt?

**Comment by Sarah-Callies** [comment]
I tried two examples，both the basic and transformer are the same error

发自我的手机

**Comment by snukky** [comment]
I just run both scripts and the subword segmented corpus files were created properly, and the training started without any errors. Maybe online resources were not available when you have tried to run the scripts, or double check if you can run subword-nmt. Maybe some dependencies are missing, but I doubt so. Please feel free to re-open if the issue still exists providing more information.
