### ISSUE TITLE
train wmt2017-uedin for amun?

### ISSUE THREAD

**Issue by chanberg** [marian-nmt/marian-examples#4]
Hi,

I was looking at the run-me.sh script for wmt2017-uedin. What parameters do I have to change to train models that can be used to translate with amun?

Thanks!

**Comment by ebektas** [comment]
amun doesn't support deep models so if you changed below to
`--enc-type bidirectional --enc-depth 1 --enc-cell-depth 4 \`
`--dec-depth 1 --dec-cell-base-depth 8 --dec-cell-high-depth 1 \`
this;
`--enc-type bidirectional`
it should work I think.

**Comment by snukky** [comment]
Actually, Amun can translate deep models of the same architecture as in the WMT17 Edinburgh systems (http://data.statmt.org/wmt17_systems/) trained with Nematus. Use `nematus2` as a scorer type. Only on CPU.
